[workspace]
resolver = "2"
members = [
  "crates/api",
  "crates/server",
  "crates/types",
  "crates/ui",
  "crates/web",
  "crates/web_client"
]

[workspace.dependencies]
diesel = { version = "2.3", features = ["postgres_backend", "uuid"] }
diesel-derive-enum = { version = "2.1", features = ["postgres"] }
dioxus = { version = "0.7.9" }
jiff = "0.2"
uuid = "1"

api = { path = "crates/api" }
server = { path = "crates/server" }
types = { path = "crates/types" }
ui = { path = "crates/ui" }
web_client = { path = "crates/web_client" }
