[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { workspace = true }
async-trait = { workspace = true }
dioxus = { workspace = true, features = ["router"] }
dioxus-sdk = { workspace = true, features = ["storage", "time"] }
pulldown-cmark = { version = "0.13", default-features = false, features = [
  "html"
] }
serde.workspace = true
serde_json.workspace = true
strum = { version = "0.28", features = ["derive"] }
