# DNS settings so that we can have e2e tests that exercise the subdomain-based
# cookbooks.

# Default to docker's embedded DNS:
server=127.0.0.11
# Point *.test to localhost:
address=/test/127.0.0.1
