#!/usr/bin/env zsh

# History
HISTFILE=$HOME/.zsh_history
HISTSIZE=100000
SAVEHIST=100000
setopt SHARE_HISTORY HIST_IGNORE_ALL_DUPS HIST_REDUCE_BLANKS EXTENDED_HISTORY INC_APPEND_HISTORY

# Behavior
setopt AUTO_CD AUTO_PUSHD PUSHD_IGNORE_DUPS INTERACTIVE_COMMENTS NO_BEEP
bindkey -e

# Completion
autoload -Uz compinit && compinit -C
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' '+l:|=* r:|=*'

# nix + direnv
source "$HOME/.nix-profile/etc/profile.d/nix.sh"
eval "$(direnv hook zsh)"

# Also load direnv eagerly, for the userEnvProbe.
eval "$(direnv export zsh)"

# Plugins
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

for f in /usr/share/doc/fzf/examples/key-bindings.zsh /usr/share/doc/fzf/examples/completion.zsh; do
    [ -f "$f" ] && source "$f"
done

eval "$(atuin init zsh --disable-up-arrow)"
eval "$(diesel completions zsh)"

# syntax-highlighting must be sourced last
source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
