[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
db = { workspace = true }
dioxus = { workspace = true, features = ["fullstack"] }
serde = { version = "1", features = ["derive"] }
server = { workspace = true, optional = true }
webauthn-rs-proto.workspace = true

[dev-dependencies]
axum = "0.8"
diesel.workspace = true
diesel-async.workspace = true
jiff.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower = { version = "0.5", features = ["util"] }
uuid.workspace = true

[features]
default = ["server", "web"]
development = []
server = ["db/server", "dep:server", "dioxus/server"]
web = []
