[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { workspace = true, optional = true }
jiff.workspace = true
serde = { version = "1", features = ["derive"] }
strum = { version = "0.28", features = ["derive"] }
uuid.workspace = true

[features]
server = ["dep:diesel"]
