[package]
name = "web"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { workspace = true }
console_error_panic_hook = "0.1"
dioxus = { workspace = true, features = ["fullstack", "router"] }
gloo-storage = "0.3"
gloo-timers = { version = "0.3", features = ["futures"] }
jiff = { workspace = true }
pulldown-cmark = { version = "0.13", default-features = false, features = [
  "html"
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
strum = { version = "0.28", features = ["derive"] }
types = { workspace = true }
ui = { workspace = true }
web-time = "1"

[features]
default = []
dev-auth = ["api/dev-auth"]
server = ["api/server", "dioxus/server"]
web = ["api/web", "dioxus/web"]
