[package]
name = "web"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-machete]
ignored = ["api"]  # Used to set web/server feature.

[dependencies]
api.workspace = true
async-trait.workspace = true
console_error_panic_hook = "0.1"
db.workspace = true
dioxus = { workspace = true, features = ["fullstack", "router"] }
server = { workspace = true, optional = true }
snafu.workspace = true
ui = { workspace = true }
webauthn-rs-proto = { workspace = true, features = ["wasm"] }

[dependencies.web-sys]
version = "0.3"
features = [
  "CredentialCreationOptions",
  "CredentialRequestOptions",
  "CredentialsContainer",
  "Navigator",
  "PublicKeyCredential",
  "PublicKeyCredentialCreationOptions",
]

[features]
default = []
server = ["api/server", "dep:server", "dioxus/server"]
web = ["api/web", "dioxus/web"]
