[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
async-trait.workspace = true
axum = "0.8"
axum_session.workspace = true
axum_session_auth.workspace = true
base64 = "0.23.1"
base64urlsafedata = "0.5.5"
db = { workspace = true, features = ["server"] }
diesel.workspace = true
diesel-async.workspace = true
diesel_migrations = "2.3"
dioxus = { workspace = true, features = ["fullstack", "server"] }
figment = { version = "0.10.19", features = ["env"] }
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio.workspace = true
tracing = "0.1"
url.workspace = true
webauthn-rs = { version = "0.5.5", features = [
  "danger-allow-state-serialisation"
] }
